#encoding: utf-8
#vim syntax=python fileencoding=utf-8 tabstop=4 expandtab shiftwidth=4
#
################################################################################
#
# MKA daemon.
# SPDX-FileCopyrightText: 2022 Technica Engineering GmbH <macsec@technica-engineering.de>
# SPDX-License-Identifier: GPL-2.0-or-later
# file: wscript
#
# © 2022 Technica Engineering GmbH.
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 2 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see https://www.gnu.org/licenses/
#
################################################################################

import os
from waflib import Build

def recurse_discover(self):
    """ Recurse all subfolders """
    curdir = self.path.abspath()
    for elem in [x for x in os.listdir(curdir) if os.path.isdir(os.path.join(curdir, x))]:
        self.recurse(elem)

def test(tst):
    # Emit friendly errors.
    isinstance(tst, Build.BuildContext) or tst.fatal("Project is not configured. Please run 'python waf configure --top=..'")

    recurse_discover(tst)

def options(opts):
    recurse_discover(opts)

def configure(conf):
    recurse_discover(conf)

